theme: jekyll-theme-minimal 
logo: https://www.google.com/imgres?q=snorlax&imgurl=https%3A%2F%2Fwww.pokemon.com%2Fstatic-assets%2Fcontent-assets%2Fcms2%2Fimg%2Fpokedex%2Fdetail%2F143.png&imgrefurl=https%3A%2F%2Fwww.pokemon.com%2Fus%2Fpokedex%2Fsnorlax&docid=G7_4VMfKYR5EPM&tbnid=0AFo4IArciVL7M&vet=12ahUKEwiG9efwpJGKAxVgEkQIHfB9PEUQM3oECB0QAA..i&w=215&h=215&hcb=2&ved=2ahUKEwiG9efwpJGKAxVgEkQIHfB9PEUQM3oECB0QAA
title: Samson's Bioinformatics Class (BIMM 143, Fall 2024) 
